app = "metropulse-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
